import fs from "fs";
import path from "path";
import { z } from "zod";
import type { YouTubeData } from "./youtube";

// Server-only loader for src/data/youtube.json, which is regenerated by
// scripts/fetch-youtube.mjs (spec: docs/superpowers/specs/2026-07-19-youtube-page-design.md).
// Parsing happens at build time; a malformed refresh fails the build instead
// of shipping a broken /youtube page. Kept apart from youtube.ts so the
// client bundle never sees fs or zod.

const YouTubeItemSchema = z.object({
    id: z.string().min(1),
    title: z.string().min(1),
    publishedAt: z.string().min(1),
    durationSec: z.number().int().min(0),
    views: z.number().int().min(0),
    thumb: z.string().startsWith("https://i.ytimg.com/"),
    status: z.enum(["live", "upcoming"]).optional(),
});

const YouTubeChannelSchema = z.object({
    id: z.string().startsWith("UC"),
    title: z.string().min(1),
    handle: z.string().startsWith("@"),
    url: z.string().startsWith("https://www.youtube.com/"),
    stats: z.object({
        subscribers: z.number().int().min(0),
        views: z.number().int().min(0),
        videos: z.number().int().min(0),
    }),
    videos: z.array(YouTubeItemSchema).max(12),
    shorts: z.array(YouTubeItemSchema).max(12),
    live: z.array(YouTubeItemSchema).max(12),
});

const YouTubeDataSchema = z.object({
    fetchedAt: z.string().min(1),
    channels: z.array(YouTubeChannelSchema).length(2),
});

const DATA_PATH = path.join(process.cwd(), "src", "data", "youtube.json");

// The YouTubeData return annotation is the drift guard: if the schema stops
// matching the hand-written types in youtube.ts, this stops compiling.
export function getYouTubeData(): YouTubeData {
    const raw = fs.readFileSync(DATA_PATH, "utf8");
    return YouTubeDataSchema.parse(JSON.parse(raw));
}
